[project]
name = "stonereader"
version = "0.1.0"
description = "An accessible interface to view Hearthstone cards, decks, and replays."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accessible-output2>=0.17",
    "hearthstone>=9.15.8",
    "hearthstone-data>=221175.1",
    "hslog>=1.18.0,<2",
    "pip",
    "psutil>=7.0,<8",
    "setuptools>=80.9.0",
    "wxpython>=4.2.5",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pyright>=1.1.402",
    "ruff>=0.11.10",
]
