"""Tests for D-19 creation-lineage tracking.

Covers the engine's ability to capture lineage on opponent-hand entities
generated inside POWER blocks (e.g. "generated by Cabal Shadow Priest").
Includes nested-block subject selection (innermost wins) and sticky-once-set
behavior (later SHOW_ENTITY does not overwrite). Friendly entities and
normal turn-start draws are explicitly excluded.

See 03-REVIEWS.md MEDIUM 03-03 for nested-block + show-entity-after additions.
"""

from __future__ import annotations

import pytest

pytest.importorskip("stonereader.services._engine")

from stonereader.models.card import Card, CardDatabase
from stonereader.services._engine import GameEngine
from stonereader.services._packets import (
    BlockEndPacket,
    BlockStartPacket,
    CreateGamePacket,
    FullEntityPacket,
    ShowEntityPacket,
)
from stonereader.services._parser import Parser


# ----- Helpers (mirror tests/test_card_browser.py:13-54) -----

_next_dbf_id = 1000  # avoid collision with test_card_browser's counter


def _make_card(
    card_id: str,
    name: str,
    cost: int = 1,
    card_type: str = "MINION",
    card_class: str = "NEUTRAL",
    card_set: str = "EXPERT1",
) -> Card:
    global _next_dbf_id
    _next_dbf_id += 1
    return Card(
        id=card_id,
        dbf_id=_next_dbf_id,
        name=name,
        cost=cost,
        attack=None,
        health=None,
        text="",
        rarity="COMMON",
        card_class=card_class,
        card_type=card_type,
        card_set=card_set,
        collectible=True,
    )


def _make_card_db(cards: list[Card]) -> CardDatabase:
    """Mirrors tests/test_card_browser.py:42-54 — bare ctor + mutate indexes."""
    db = CardDatabase()
    for card in cards:
        db.cards_by_id[card.id] = card
        db.cards_by_dbf_id[card.dbf_id] = card
        db.cards_by_name[card.name.lower()] = card
        db.cards_by_class.setdefault(card.card_class, []).append(card)
        db.cards_by_type.setdefault(card.card_type, []).append(card)
        db.cards_by_set.setdefault(card.card_set, []).append(card)
        db.cards_by_cost.setdefault(card.cost, []).append(card)
        if card.collectible:
            db.collectible_cards.append(card)
    return db


def test_lineage_recorded() -> None:
    """BLOCK_START POWER subject + FULL_ENTITY in opponent HAND records lineage."""
    cabal = _make_card("EX1_339", "Cabal Shadow Priest", cost=6)
    card_db = _make_card_db([cabal])
    engine = GameEngine(card_db=card_db)

    # Two real-account players (forces SHOW_ENTITY fallback path NOT to fire
    # on FULL_ENTITY; we want CONTROLLER=2 to be opponent for friendly=1).
    engine.apply(
        CreateGamePacket(
            packet_id=0,
            game_entity_id=1,
            players=(
                (2, 1, "LocalPlayer", 144115198130930503, 1),
                (3, 2, "Opponent", 144115198130930504, 2),
            ),
        )
    )
    # Pre-record the subject (Cabal) as known in PLAY for player 1 (friendly).
    engine.apply(
        FullEntityPacket(
            packet_id=1,
            entity_id=10,
            card_id="EX1_339",
            tags={"CONTROLLER": 1, "ZONE": 1},  # 1 = PLAY
        )
    )
    # Open a POWER block whose subject is the Cabal entity.
    engine.apply(
        BlockStartPacket(packet_id=2, block_type="POWER", entity_id=10)
    )
    # FULL_ENTITY arrives in opponent HAND inside the POWER block.
    engine.apply(
        FullEntityPacket(
            packet_id=3,
            entity_id=20,
            card_id="",  # opponent's card_id is hidden; lineage still captures
            tags={"CONTROLLER": 2, "ZONE": 3},  # 3 = HAND
        )
    )
    engine.apply(BlockEndPacket(packet_id=4, block_type="POWER", entity_id=10))

    state = engine.current_state
    assert state is not None
    opponent_hand = state.opponent_hand
    assert len(opponent_hand) == 1, (
        f"Expected 1 opponent-hand entity, got {len(opponent_hand)}"
    )
    assert opponent_hand[0] is not None
    assert opponent_hand[0].entity_id == 20
    assert opponent_hand[0].creation_lineage == "Cabal Shadow Priest"


def test_no_lineage_for_normal_draw() -> None:
    """Cards drawn outside any POWER block do NOT receive lineage."""
    engine = GameEngine()
    engine.apply(
        CreateGamePacket(
            packet_id=0,
            game_entity_id=1,
            players=(
                (2, 1, "LocalPlayer", 144115198130930503, 1),
                (3, 2, "Opponent", 144115198130930504, 2),
            ),
        )
    )
    # FULL_ENTITY arrives in opponent HAND with NO POWER block open.
    engine.apply(
        FullEntityPacket(
            packet_id=1,
            entity_id=30,
            card_id="",
            tags={"CONTROLLER": 2, "ZONE": 3},
        )
    )

    state = engine.current_state
    assert state is not None
    for ent in state.opponent_hand:
        assert ent is not None
        assert ent.creation_lineage == "", (
            f"Expected no lineage for normal draw, got '{ent.creation_lineage}'"
        )


def test_no_lineage_for_friendly() -> None:
    """Same generation event for FRIENDLY entity → no lineage (we only track opponent)."""
    cabal = _make_card("EX1_339", "Cabal Shadow Priest", cost=6)
    card_db = _make_card_db([cabal])
    engine = GameEngine(card_db=card_db)
    engine.apply(
        CreateGamePacket(
            packet_id=0,
            game_entity_id=1,
            players=(
                (2, 1, "LocalPlayer", 144115198130930503, 1),
                (3, 2, "Opponent", 144115198130930504, 2),
            ),
        )
    )
    engine.apply(
        FullEntityPacket(
            packet_id=1,
            entity_id=10,
            card_id="EX1_339",
            tags={"CONTROLLER": 1, "ZONE": 1},
        )
    )
    engine.apply(BlockStartPacket(packet_id=2, block_type="POWER", entity_id=10))
    # Generated entity ends up in FRIENDLY hand (CONTROLLER=1 == friendly).
    engine.apply(
        FullEntityPacket(
            packet_id=3,
            entity_id=40,
            card_id="",
            tags={"CONTROLLER": 1, "ZONE": 3},
        )
    )
    engine.apply(BlockEndPacket(packet_id=4, block_type="POWER", entity_id=10))

    state = engine.current_state
    assert state is not None
    # Friendly hand entity must NOT appear in opponent_hand reconstruction.
    for ent in state.opponent_hand:
        assert ent is not None
        assert ent.entity_id != 40
    # And the bookkeeping dict for entity 40 must NOT have creation_lineage set.
    assert "creation_lineage" not in engine._entities[40]


def test_lineage_nested_blocks() -> None:
    """Nested POWER blocks: lineage points at the INNERMOST subject (top of stack).

    Scenario: outer block subject is Wand of Disintegration; inner block
    subject is Cabal Shadow Priest. FULL_ENTITY arrives inside the inner
    block. The captured lineage MUST be 'Cabal Shadow Priest', not 'Wand'.
    """
    wand = _make_card("YOG_516", "Wand of Disintegration", cost=2)
    cabal = _make_card("EX1_339", "Cabal Shadow Priest", cost=6)
    card_db = _make_card_db([wand, cabal])
    engine = GameEngine(card_db=card_db)
    engine.apply(
        CreateGamePacket(
            packet_id=0,
            game_entity_id=1,
            players=(
                (2, 1, "LocalPlayer", 144115198130930503, 1),
                (3, 2, "Opponent", 144115198130930504, 2),
            ),
        )
    )
    # Pre-record both subject entities.
    engine.apply(
        FullEntityPacket(
            packet_id=1, entity_id=50, card_id="YOG_516",
            tags={"CONTROLLER": 1, "ZONE": 1},
        )
    )
    engine.apply(
        FullEntityPacket(
            packet_id=2, entity_id=51, card_id="EX1_339",
            tags={"CONTROLLER": 1, "ZONE": 1},
        )
    )
    # Outer block: Wand.
    engine.apply(BlockStartPacket(packet_id=3, block_type="POWER", entity_id=50))
    # Inner block: Cabal.
    engine.apply(BlockStartPacket(packet_id=4, block_type="POWER", entity_id=51))
    # Generated entity arrives inside the INNER block.
    engine.apply(
        FullEntityPacket(
            packet_id=5, entity_id=52, card_id="",
            tags={"CONTROLLER": 2, "ZONE": 3},
        )
    )
    engine.apply(BlockEndPacket(packet_id=6, block_type="POWER", entity_id=51))
    engine.apply(BlockEndPacket(packet_id=7, block_type="POWER", entity_id=50))

    state = engine.current_state
    assert state is not None
    gen = next((e for e in state.opponent_hand if e is not None and e.entity_id == 52), None)
    assert gen is not None, (
        f"Expected entity 52 in opponent_hand, got "
        f"{[e.entity_id for e in state.opponent_hand if e is not None]}"
    )
    assert gen.creation_lineage == "Cabal Shadow Priest", (
        f"Expected innermost subject 'Cabal Shadow Priest', got '{gen.creation_lineage}'"
    )


def test_show_entity_after_lineage() -> None:
    """A hidden hand entity gets lineage on FULL_ENTITY arrival; later
    SHOW_ENTITY reveals card_id, but lineage is preserved unchanged.

    Pre-resolves friendly_player via an initial friendly mulligan SHOW_ENTITY
    so the WR-02 SHOW_ENTITY-into-HAND fallback does NOT misfire when the
    opponent's generated card is later revealed (the fallback would
    otherwise flip friendly to 2 and remove entity 60 from opponent_hand).
    """
    cabal = _make_card("EX1_339", "Cabal Shadow Priest", cost=6)
    revealed = _make_card("CS2_029", "Fireball", cost=4)
    friendly_mull = _make_card("CS2_032", "Flamestrike", cost=7)
    card_db = _make_card_db([cabal, revealed, friendly_mull])
    engine = GameEngine(card_db=card_db)
    engine.apply(
        CreateGamePacket(
            packet_id=0,
            game_entity_id=1,
            players=(
                (2, 1, "LocalPlayer", 144115198130930503, 1),
                (3, 2, "Opponent", 144115198130930504, 2),
            ),
        )
    )
    # Pre-resolve friendly_player: friendly's mulligan card is revealed in
    # HAND (CONTROLLER=1). This locks _friendly_player_resolved = True so
    # later SHOW_ENTITY events do not retrigger the fallback.
    engine.apply(
        FullEntityPacket(
            packet_id=1, entity_id=99, card_id="",
            tags={"CONTROLLER": 1, "ZONE": 3},
        )
    )
    engine.apply(
        ShowEntityPacket(
            packet_id=2, entity_id=99, card_id="CS2_032",
            tags={"CONTROLLER": 1, "ZONE": 3},
        )
    )
    assert engine._friendly_player_resolved is True
    assert engine._friendly_player_id == 1

    engine.apply(
        FullEntityPacket(
            packet_id=3, entity_id=10, card_id="EX1_339",
            tags={"CONTROLLER": 1, "ZONE": 1},
        )
    )
    engine.apply(BlockStartPacket(packet_id=4, block_type="POWER", entity_id=10))
    # FULL_ENTITY in opponent HAND inside POWER block — captures lineage.
    engine.apply(
        FullEntityPacket(
            packet_id=5, entity_id=60, card_id="",
            tags={"CONTROLLER": 2, "ZONE": 3},
        )
    )
    engine.apply(BlockEndPacket(packet_id=6, block_type="POWER", entity_id=10))
    # Verify lineage is set BEFORE the reveal.
    state = engine.current_state
    assert state is not None
    gen = next(e for e in state.opponent_hand if e is not None and e.entity_id == 60)
    assert gen.creation_lineage == "Cabal Shadow Priest"
    assert gen.card_id == ""  # still hidden

    # Later (turns later, outside any block): SHOW_ENTITY reveals the card.
    # With friendly already resolved, the fallback does NOT fire — entity 60
    # stays in opponent_hand, card_id updates, lineage is preserved.
    engine.apply(
        ShowEntityPacket(
            packet_id=7, entity_id=60, card_id="CS2_029",
            tags={"CONTROLLER": 2, "ZONE": 3},
        )
    )
    state = engine.current_state
    assert state is not None
    gen = next(e for e in state.opponent_hand if e is not None and e.entity_id == 60)
    # Card_id is now revealed BUT lineage is preserved (sticky).
    assert gen.card_id == "CS2_029", f"Expected reveal, got card_id='{gen.card_id}'"
    assert gen.creation_lineage == "Cabal Shadow Priest", (
        f"Lineage must persist after SHOW_ENTITY; got '{gen.creation_lineage}'"
    )


def test_reconnect_drops_lineage(power_log_fixture) -> None:
    """After a reconnect (second CREATE_GAME), prior lineage is dropped.

    The 4 captured fixtures are vs-AI Constructed games without Discover /
    generation events, so no lineage is expected for any opponent-hand
    entity. This test specifically verifies that even AFTER a reconnect
    boundary, no stale lineage leaks into the second game.
    """
    path = power_log_fixture("reconnect.log")  # skips if absent
    parser = Parser()
    engine = GameEngine()
    for line in path.read_text(encoding="utf-8").splitlines():
        for pkt in parser.feed_line(line):
            engine.apply(pkt)
    state = engine.current_state
    assert state is not None
    for ent in state.opponent_hand:
        assert ent is not None
        assert ent.creation_lineage == "", (
            f"Expected no lineage in reconnect fixture, got entity {ent.entity_id} "
            f"with lineage '{ent.creation_lineage}'"
        )
